In [2]:
import osmnx as ox
import geopandas

In [ ]:
place_name = " Kassel, Germany", 

geo_method = ox.geocode_to_gdf(place_name)
geo_method

In [6]:
place_name = "Kassel"

# tags = {"boundary":"postal_code", }
tags = {"admin_level":"5" }


polygon_method =ox.features_from_place(place_name,tags)

len(polygon_method)
polygon_method

C:\Users\hamud\AppData\Roaming\Python\Python312\site-packages\jupyter_client\session.py:200: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)  # noqa

,,geometry,name,boundary,nodes,admin_level,ways,TMC:cid_58:tabcd_1:Class,TMC:cid_58:tabcd_1:LCLversion,TMC:cid_58:tabcd_1:LocationCode,de:amtlicher_gemeindeschluessel,de:regionalschluessel,name:ru,ref:nuts,ref:nuts:2,type,wikidata,wikipedia
element_type,osmid,,,,,,,,,,,,,,,,,
relation,286675,"POLYGON ((8.47752 50.97017, 8.47737 50.97063, ...",Regierungsbezirk Kassel,administrative,"[[[9701442003, 9701442002, 9701486719, 9701486...",5,"[1055814405, 1234256383, 1073846128, 51777175,...",Area,8.00,285,066,066,Кассель,DE73,DE73,boundary,Q7928,de:Regierungsbezirk Kassel

C:\Users\hamud\AppData\Roaming\Python\Python312\site-packages\jupyter_client\session.py:200: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)  # noqa

In [7]:
place_name = "Kassel"

tags = {"boundary":"postal_code", }

polygon_method =ox.features_from_place(place_name,tags)

len(polygon_method)
polygon_method

C:\Users\hamud\AppData\Roaming\Python\Python312\site-packages\jupyter_client\session.py:200: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)  # noqa
C:\Users\hamud\AppData\Roaming\Python\Python312\site-packages\jupyter_client\session.py:200: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)  # noqa

                                                                     nodes  \
element_type osmid
way          79122997    [924504213, 925551338, 925551344, 924504382, 9...
             79122998         [324038510, 924504293, 924504436, 924504231]
             79122999    [924504318, 924504156, 924504363, 924504283, 4...
             79123002    [323579051, 925551355, 925551301, 924504320, 9...
             79123005         [924504188, 925551318, 925551317, 924504250]
             79123006        [924504213, 924504209, 1244818257, 924504450]
             79123008                    [924504250, 925551339, 924504417]
             79123010    [924504450, 924504256, 924504137, 925551353, 9...
             79123013    [323641426, 924504401, 924504165, 924504169, 9...
             79123015    [324087097, 2525725479, 2525725480, 924504312,...
             79123016    [924504417, 2853191394, 2816474380, 924504426,...
             79123018    [924504250, 3378286795, 2836131726, 2816659580...
             79123019    [323784463, 924504277, 924504428, 924504216, 9...
             79123020                  [9489636756, 924504380, 2614739300]
             79123023    [924504417, 924504180, 2852866605, 2853191395,...
             79123024    [924504450, 2610632905, 2610632908, 924504325,...
             79123028    [323898223, 924504356, 924504129, 9463521698, ...
             79123029    [924504177, 924504281, 1219576228, 924504431, ...
             79123031    [924504318, 924504218, 924504391, 924504447, 3...
             79123032    [924504177, 2828448059, 2816642158, 3570989713...
             255788790   [2614739300, 2816680326, 2816680327, 281668032...
             277135760   [324034025, 2924815277, 2816699506, 2924815278...
             277148054   [324072737, 10171746578, 10173302264, 10171746...
             288928781   [323672263, 2828503223, 2924815281, 2157794266...
             376489040   [323454254, 3799001213, 3880279404, 3880279405...
             378869490   [9487193854, 10171746583, 10171746584, 3822297...
             453136782                              [925551287, 924504188]
             453136784   [924504231, 924504420, 924504196, 924504365, 9...
             673291204   [3851865788, 6305254163, 6305254162, 630525416...
             1178254614                            [324124830, 9508294635]
             1214236282  [924504395, 924504159, 924504334, 924504101, 1...
relation     1189961     [[[323334067, 9505549832, 9505549831, 32354020...
             1189962     [[[924504417, 2853191394, 2816474380, 92450442...
             1189963     [[[323672263, 2828503223, 2924815281, 21577942...
             1189964     [[[324087097, 2525725479, 2525725480, 92450431...
             1189965     [[[324121906, 323695158, 9508020043, 950802004...
             1189966     [[[925551287, 924504188], [925551287, 22939621...
             1189968     [[[324121190, 9492052594, 9492052593, 94920525...
             1189969     [[[924504450, 924504256, 924504137, 925551353,...
             1189970     [[[925551287, 2293962110, 2293962111, 22939621...
             1189971     [[[924504318, 924504156, 924504363, 924504283,...
             1189972     [[[924504417, 924504180, 2852866605, 285319139...
             1189973     [[[3421902269, 323868632, 323901323, 323928841...
             1202073     [[[323684606, 932016020, 932015950, 932015982,...
             3356213     [[[9476700352, 9476700351, 9476700350, 9476700...
             3356552     [[[323318896, 9492310366, 323396304, 323725729...
             3356553     [[[9483734002, 9483734001, 9483734000, 9483733...
             3356554     [[[323334067, 9487089831, 9487089830, 94870898...
             3356556     [[[671187076, 9577862348, 9577862347, 67118707...
             3356590     [[[3421902269, 323868632, 323901323, 323928841...
             3356591     [[[9489657001, 9489694505, 9489694504, 9489694...
             3356593     [[[669376595, 9476464967, 9476464966, 66937659...
             3356602     [[[323355255, 323878681, 323877738, 323300533,...

                            boundary  \
element_type osmid
way          79122997    postal_code
             79122998    postal_code
             79122999    postal_code
             79123002    postal_code
             79123005    postal_code
             79123006    postal_code
             79123008    postal_code
             79123010    postal_code
             79123013    postal_code
             79123015    postal_code
             79123016    postal_code
             79123018    postal_code
             79123019    postal_code
             79123020    postal_code
             79123023    postal_code
             79123024    postal_code
             79123028    postal_code
             79123029    postal_code
             79123031    postal_code
             79123032    postal_code
             255788790   postal_code
             277135760   postal_code
             277148054   postal_code
             288928781   postal_code
             376489040   postal_code
             378869490   postal_code
             453136782   postal_code
             453136784   postal_code
             673291204   postal_code
             1178254614  postal_code
             1214236282  postal_code
relation     1189961     postal_code
             1189962     postal_code
             1189963     postal_code
             1189964     postal_code
             1189965     postal_code
             1189966     postal_code
             1189968     postal_code
             1189969     postal_code
             1189970     postal_code
             1189971     postal_code
             1189972     postal_code
             1189973     postal_code
             1202073     postal_code
             3356213     postal_code
             3356552     postal_code
             3356553     postal_code
             3356554     postal_code
             3356556     postal_code
             3356590     postal_code
             3356591     postal_code
             3356593     postal_code
             3356602     postal_code

                                                                  geometry  \
element_type osmid
way          79122997    LINESTRING (9.46549 51.32477, 9.46536 51.32438...
             79122998    LINESTRING (9.37797 51.33190, 9.39812 51.33115...
             79122999    LINESTRING (9.45462 51.30333, 9.45814 51.29989...
             79123002    LINESTRING (9.53065 51.31812, 9.52890 51.31729...
             79123005    LINESTRING (9.44622 51.31502, 9.44622 51.31475...
             79123006    LINESTRING (9.46549 51.32477, 9.46484 51.32495...
             79123008    LINESTRING (9.44852 51.31338, 9.45047 51.31329...
             79123010    LINESTRING (9.46329 51.32532, 9.46162 51.32328...
             79123013    LINESTRING (9.36284 51.29899, 9.41391 51.29857...
             79123015    LINESTRING (9.50392 51.34279, 9.50242 51.34126...
             79123016    LINESTRING (9.47842 51.31190, 9.47844 51.31151...
             79123018    LINESTRING (9.44852 51.31338, 9.44851 51.31320...
             79123019    LINESTRING (9.45192 51.26591, 9.45545 51.26802...
             79123020    LINESTRING (9.49019 51.28411, 9.49057 51.28570...
             79123023    LINESTRING (9.47842 51.31190, 9.47997 51.31182...
             79123024    LINESTRING (9.46329 51.32532, 9.46235 51.32598...
             79123028    LINESTRING (9.47339 51.34550, 9.47322 51.34348...
             79123029    LINESTRING (9.50302 51.32089, 9.50218 51.32104...
             79123031    LINESTRING (9.45462 51.30333, 9.45187 51.30319...
             79123032    LINESTRING (9.50302 51.32089, 9.50571 51.32023...
             255788790   LINESTRING (9.49052 51.28672, 9.49908 51.28740...
             277135760   LINESTRING (9.51128 51.34253, 9.51161 51.34271...
             277148054   LINESTRING (9.50720 51.27449, 9.50675 51.27398...
             288928781   LINESTRING (9.51053 51.34398, 9.51046 51.34426...
             376489040   LINESTRING (9.55506 51.35222, 9.55412 51.35382...
             378869490   LINESTRING (9.51484 51.26551, 9.51494 51.26567...
             453136782     LINESTRING (9.44648 51.31666, 9.44622 51.31502)
             453136784   LINESTRING (9.40931 51.32642, 9.40990 51.32229...
             673291204   LINESTRING (9.44295 51.35158, 9.44130 51.35125...
             1178254614    LINESTRING (9.53102 51.36353, 9.53105 51.36349)
             1214236282  LINESTRING (9.48851 51.32364, 9.48632 51.32327...
relation     1189961     POLYGON ((9.48863 51.29236, 9.48877 51.29280, ...
             1189962     POLYGON ((9.44852 51.31338, 9.45047 51.31329, ...
             1189963     POLYGON ((9.48528 51.37824, 9.48549 51.37828, ...
             1189964     POLYGON ((9.50302 51.32089, 9.50353 51.32139, ...
             1189965     POLYGON ((9.36906 51.34865, 9.36992 51.34926, ...
             1189966     POLYGON ((9.35102 51.30713, 9.35181 51.30745, ...
             1189968     POLYGON ((9.36240 51.29257, 9.36244 51.29263, ...
             1189969     POLYGON ((9.44622 51.31502, 9.44648 51.31666, ...
             1189970     POLYGON ((9.40931 51.32642, 9.41014 51.32794, ...
             1189971     POLYGON ((9.43034 51.30008, 9.43104 51.30072, ...
             1189972     POLYGON ((9.47574 51.32076, 9.47760 51.32061, ...
             1189973     POLYGON ((9.46549 51.32477, 9.46577 51.32548, ...
             1202073     POLYGON ((9.53069 51.36581, 9.53083 51.36595, ...
             3356213     POLYGON ((9.25028 51.29281, 9.25034 51.29281, ...
             3356552     POLYGON ((9.32666 51.25763, 9.32750 51.25907, ...
             3356553     POLYGON ((9.51484 51.26551, 9.51494 51.26567, ...
             3356554     POLYGON ((9.55372 51.29026, 9.55510 51.29104, ...
             3356556     POLYGON ((9.35176 51.35982, 9.35180 51.36138, ...
             3356590     POLYGON ((9.43132 51.37985, 9.43148 51.37978, ...
             3356591     POLYGON ((9.46051 51.24396, 9.46057 51.24409, ...
             3356593     POLYGON ((9.28348 51.34026, 9.28357 51.34062, ...
             3356602     POLYGON ((9.53065 51.31812, 9.53102 51.31840, ...

                                                                      note  \
element_type osmid
way          79122997                                                  NaN
             79122998                                                  NaN
             79122999                                                  NaN
             79123002    Im Bereich der Leipziger Straße sollte nun die...
             79123005                                                  NaN
             79123006                                                  NaN
             79123008                                                  NaN
             79123010                                                  NaN
             79123013                                                  NaN
             79123015                                                  NaN
             79123016                                                  NaN
             79123018                                                  NaN
             79123019                                                  NaN
             79123020                                                  NaN
             79123023                                                  NaN
             79123024                                                  NaN
             79123028                                                  NaN
             79123029                                                  NaN
             79123031                                                  NaN
             79123032                                                  NaN
             255788790                                                 NaN
             277135760                                                 NaN
             277148054                                                 NaN
             288928781                                                 NaN
             376489040                                                 NaN
             378869490                                                 NaN
             453136782                                                 NaN
             453136784                                                 NaN
             673291204                                                 NaN
             1178254614                                                NaN
             1214236282                                                NaN
relation     1189961                                          34123 Kassel
             1189962                                          34121 Kassel
             1189963                                34233 Kassel, Fuldatal
             1189964                                          34125 Kassel
             1189965                                          34128 Kassel
             1189966                                          34131 Kassel
             1189968                                          34132 Kassel
             1189969                                          34119 Kassel
             1189970                                          34130 Kassel
             1189971                                          34134 Kassel
             1189972                                          34117 Kassel
             1189973                                          34127 Kassel
             1202073                                     34355 Staufenberg
             3356213                                     34270 Schauenburg
             3356552                                        34225 Baunatal
             3356553                                       34253 Lohfelden
             3356554                                       34260 Kaufungen
             3356556                                         34292 Ahnatal
             3356590                                         34246 Vellmar
             3356591                                      34277 Fuldabrück
             3356593                                    34317 Habichtswald
             3356602                                       34266 Niestetal

                                                                     fixme  \
element_type osmid
way          79122997                                                  NaN
             79122998                                                  NaN
             79122999                                                  NaN
             79123002                                                  NaN
             79123005                                                  NaN
             79123006                                                  NaN
             79123008                                                  NaN
             79123010                                                  NaN
             79123013                                                  NaN
             79123015                                                  NaN
             79123016                                                  NaN
             79123018                                                  NaN
             79123019                                                  NaN
             79123020                                                  NaN
             79123023                                                  NaN
             79123024                                                  NaN
             79123028                                                  NaN
             79123029                                                  NaN
             79123031                                                  NaN
             79123032                                                  NaN
             255788790                                                 NaN
             277135760                                                 NaN
             277148054                                                 NaN
             288928781                                       seems invalid
             376489040                                                 NaN
             378869490                                                 NaN
             453136782                                                 NaN
             453136784                                                 NaN
             673291204                                                 NaN
             1178254614                                                NaN
             1214236282                                                NaN
relation     1189961                                                   NaN
             1189962                                                   NaN
             1189963     "Arbeiterwohnhäuser Kragenhof" also as Fuldata...
             1189964                                                   NaN
             1189965                                                   NaN
             1189966                                                   NaN
             1189968                                                   NaN
             1189969                                                   NaN
             1189970                                                   NaN
             1189971                                                   NaN
             1189972                                                   NaN
             1189973                                                   NaN
             1202073                                                   NaN
             3356213                                                   NaN
             3356552                                                   NaN
             3356553                                                   NaN
             3356554                                                   NaN
             3356556                                                   NaN
             3356590                                                   NaN
             3356591                                                   NaN
             3356593                                                   NaN
             3356602                                                   NaN

                                                                      ways  \
element_type osmid
way          79122997                                                  NaN
             79122998                                                  NaN
             79122999                                                  NaN
             79123002                                                  NaN
             79123005                                                  NaN
             79123006                                                  NaN
             79123008                                                  NaN
             79123010                                                  NaN
             79123013                                                  NaN
             79123015                                                  NaN
             79123016                                                  NaN
             79123018                                                  NaN
             79123019                                                  NaN
             79123020                                                  NaN
             79123023                                                  NaN
             79123024                                                  NaN
             79123028                                                  NaN
             79123029                                                  NaN
             79123031                                                  NaN
             79123032                                                  NaN
             255788790                                                 NaN